#!/usr/bin/env bash
# Keep the "only Cloudflare may reach ports 80/443" rules and the nginx real_ip
# list in sync with Cloudflare's published ranges.
#
#   scripts/cloudflare-ips.sh --nginx      rewrite config/nginx/snippets/cloudflare-realip.conf
#   scripts/cloudflare-ips.sh --ufw        ufw allow 80,443 from each range
# Flags can be combined. Run as root for --ufw.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SNIPPET="${REPO_DIR}/config/nginx/snippets/cloudflare-realip.conf"

V4="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v4)" || { echo "fetch ips-v4 failed"; exit 1; }
V6="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v6)" || { echo "fetch ips-v6 failed"; exit 1; }
[[ -n "$V4" && -n "$V6" ]] || { echo "empty IP list, aborting"; exit 1; }

do_nginx() {
  {
    echo "# Restore the reader's real IP from Cloudflare. Rate limits, logs and"
    echo "# WordPress (\$_SERVER['REMOTE_ADDR']) all depend on this."
    echo "# Generated by scripts/cloudflare-ips.sh on $(date -u +%F) — do not edit by hand."
    echo "# Source: https://www.cloudflare.com/ips-v4  https://www.cloudflare.com/ips-v6"
    echo
    for ip in $V4 $V6; do echo "set_real_ip_from ${ip};"; done
    echo
    echo "real_ip_header    CF-Connecting-IP;"
    echo "real_ip_recursive on;"
  } > "$SNIPPET"
  echo "wrote $SNIPPET"
}

do_ufw() {
  # Remove previous Cloudflare rules (tagged by comment), then re-add.
  while read -r num; do ufw --force delete "$num" >/dev/null; done < <(
    ufw status numbered | grep 'cloudflare' | sed -E 's/^\[ *([0-9]+)\].*/\1/' | sort -rn)
  for ip in $V4 $V6; do
    ufw allow proto tcp from "$ip" to any port 80,443 comment 'cloudflare' >/dev/null
  done
  echo "ufw: allowed 80/443 from $(echo "$V4 $V6" | wc -w) Cloudflare ranges"
}

[[ $# -gt 0 ]] || { echo "usage: $0 [--nginx] [--ufw]"; exit 1; }
for arg in "$@"; do
  case "$arg" in
    --nginx) do_nginx ;;
    --ufw)   do_ufw ;;
    --iptables)
      echo "skipping --iptables (ufw handles 80/443 on this stack)" >&2
      ;;
    *) echo "unknown flag $arg"; exit 1 ;;
  esac
done
